### ISSUE TITLE
Maps API key available

### ISSUE THREAD

**Issue by kQuintal** [Neappoli/website#1]
As this is a public Repo, our Maps key should not be publicly available.

Either need to put this in environment variables, another file tracked with .gitignore, or another potential solution.

https://github.com/Neappoli/website/blob/f7dce91780f7fbd38a1f4eb4e6ff89f5cb4386fc/dashboard/src/components/GoogleMap.js#L66

**Comment by gtupak** [comment]
It's ok. The key is restricted to work only from neappoli.com. It has* to stay on the front end because it's a js library.

**Comment by kQuintal** [comment]
oh! I remember you mentioning this previously, my bad. I'll close the issue.
